### ISSUE TITLE
Issue with /modify_profile API

### ISSUE THREAD

**Issue by ekanshsinghal** [ekanshsinghal/se-group26-proj1#17]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/15945880/194776766-8732547f-c71a-4b92-b2a5-2cd515a2ae07.png">

**Comment by rahulrk2303** [comment]
Can you please check if you are passing the "_id" as part of the request?

**Comment by rahulrk2303** [comment]
The flow should be like:
1. User goes to profile page. The view_profile API should check if the user already has a profile or not.
2. If first time profile is not present, it will return an empty string
3. If front end receives an empty string, this means profile is not present and this should call the create_profile api.
4. User creates the profile.
5. Next time if profile is present, the view_profile API will send the profile data as result.
6. If user wants to make any changes, this should go to modify profile API.

**Comment by rahulrk2303** [comment]
Looks like the issue was with the ObjectID(_id). We were previously checking with the _id as a string. Updated the code.

**Comment by rahulrk2303** [comment]
Verified view, create, modify, delete works.

**Comment by rahulrk2303** [comment]
Closing issue
