### ISSUE TITLE
Decision - Accept and reject color change

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/se-group26-proj1#2]
The decision column should show green and red colored cards based on the status (accept or reject)

**Comment by ekanshsinghal** [comment]
[22bb1df](https://github.com/ekanshsinghal/se-group26-proj1/commit/22bb1dfb98e695e0b5fff4c74f3eee7c11fd9f61)
<img width="365" alt="image" src="https://user-images.githubusercontent.com/15945880/194443108-dfcd70aa-4775-4849-81c1-41781f1d4694.png">

**Comment by rahulrk2303** [comment]
The card colors look good.
