### ISSUE TITLE
Saved applications

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/se-group26-proj1#3]
Ideas:

1. While adding an application, create a new option in "Status" called "Interested" or "Save for later". The applications added with this status should go to the "Saved applications" page.
2. Add an option to directly add applications to "Saved Applications" with just the "Interested" or "Save for later" status.

**Comment by ekanshsinghal** [comment]
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/15945880/194443222-993d0aee-8f7d-4992-be55-aa0a8f616355.png">

Done 2. Not doing 1.

**Comment by rahulrk2303** [comment]
Approach 2 makes sense.
