### ISSUE TITLE
Nav options not being displayed. 

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/se-group26-proj1#4]
Nav options should be displayed by default. 

![image](https://user-images.githubusercontent.com/30636208/194399910-9e5c028b-caf2-45ee-a775-476cffdd0741.png)

**Comment by ekanshsinghal** [comment]
Give specific steps to replicate

**Comment by rahulrk2303** [comment]
Refer to this video. (slowed down)
https://user-images.githubusercontent.com/30636208/194678359-0fb7bf4a-af33-4336-a76f-f87fb54a2ed4.mp4

**Comment by ekanshsinghal** [comment]
Fixed
