### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/se-group26-proj1#5]
![image](https://user-images.githubusercontent.com/30636208/194403827-588fd540-ae22-4213-8ef0-e303c4ba6e65.png)

**Comment by ekanshsinghal** [comment]
[22bb1df](https://github.com/ekanshsinghal/se-group26-proj1/commit/22bb1dfb98e695e0b5fff4c74f3eee7c11fd9f61)

**Comment by rahulrk2303** [comment]
Verified. Working good!
