### ISSUE TITLE
Generate docs for frontend and backend

### ISSUE THREAD

**Issue by rahulrk2303** [ekanshsinghal/se-group26-proj1#6]
Doc generation for python and react js
Python can use Sphinx,

**Comment by gowtham-sathyan** [comment]
Backend documentation done. Automation pending

**Comment by rahulrk2303** [comment]
Creating a new task for automation using Git actions workflow.

**Comment by gowtham-sathyan** [comment]
Completed Git actions workflow for backend docs generation. Only frontend pending.

**Comment by ekanshsinghal** [comment]
Added frontend docs
